### ISSUE TITLE
Patreon item creation boost

### ISSUE THREAD

**Issue by kennnyshiwa** [kennnyshiwa/gobcog#7]
https://media.kstj.us/AntiqueRoastedQuinquespinosus.png

1 item per week
ilevel 1 
can only equip if they have an active sub
Dont reset at rebirth 
they get a stats pool they can use, so should they choose they can make 1 stat like 75,  and the other 0 or all 15 etc etc

**Comment by Drapersniper** [comment]
Kenny said GH sucks :aha:
